
name : Alpha

on :
  pull_request :
    branches:
      - beta

env:
  CARGO_TERM_COLOR: always

jobs :

  desktop_fast:
    if: "contains( github.event.head_commit.message, '[test_rapid]' )"
    uses: Wandalen/game_chess/.github/workflows/DesktopCommon.yml@main
    with:
      artifacts: 'false'
      build: 'fast'
      toolchain: 'stable'
  desktop:
    if: "contains( github.event.head_commit.message, '[build]' ) || startsWith( github.event.head_commit.message, 'Merge ' )"
    uses: Wandalen/game_chess/.github/workflows/DesktopCommon.yml@main
    with:
      artifacts: 'false'
      build: 'slow'
      toolchain: 'nightly'

  # web_fast:
  #   if: "contains( github.event.head_commit.message, '[test_rapid]' )"
  #   uses: Wandalen/game_chess/.github/workflows/WebCommon.yml@main
  #   with:
  #     artifacts: 'false'
  #     build: 'fast'
  #     toolchain: 'stable'
  # web:
  #   if: "contains( github.event.head_commit.message, '[build]' ) || startsWith( github.event.head_commit.message, 'Merge ' )"
  #   uses: Wandalen/game_chess/.github/workflows/WebCommon.yml@main
  #   with:
  #     artifacts: 'true'
  #     build: 'slow'
  #     toolchain: 'nightly'

  # forward :
  #   # needs: [ desktop, web ]
  #   needs: [ desktop ]
  #   runs-on : ubuntu-latest
  #   steps :
  #     - uses: actions/checkout@v2
  #     - uses : everlytic/branch-merge@1.1.2
  #       with :
  #         github_token : ${{ secrets.PRIVATE_GITHUB_TOKEN }}
  #         source_ref : alpha
  #         target_branch : beta
  #         commit_message_template : 'Merge {source_ref} into {target_branch} [Automated]'


  forward :
    # needs: [ desktop, web ]
    needs: [ desktop ]
    runs-on : ubuntu-latest
    steps :
      - name: Automerge
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          number: ${{ github.event.number }}
          method: merge

